### ISSUE TITLE
SSL Error with Termux, pip, ssl package

### ISSUE THREAD

**Issue by mondaysunrise** [leouieda/website#233]
Dear leouieda,

amazing idea.

For me it fails with newest versions of Termux and python during pip install ...

like this:

pip install numpy
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.

Also, I can't even do "import ssl" within python on console.

Do you have any idea what went wrong or is this an issue which should be reported to Termux.

Additionally, Termux doesnt seem to maintain -dev packages, but they are included in the package name itself if I understand that right, e.g. no need to install python-dev anymore.

Kind regards,

**Comment by leouieda** [comment]
Hi @mondaysunrise sorry but I haven't been using this setup for quite a while. I imagine that pip has been updated and termux never kept up. But I've never seen that error message before. Have you tried googling for the that particular message?

**Comment by leouieda** [comment]
Haven't had a response in a year so I'm closing this. Feel free to reopen if there is renewed interest.

**Comment by Igittigitt24** [comment]
I have the same problem. And it is Dec 12 2022.
There must be an error in _ssl
Can't be found.
What can I do?
I want to use python in termux including all modules...
